language: go
sudo: required
go:
- 1.11
install:
  - go get github.com/gorilla/websocket
  - go get github.com/gomodule/redigo/redis
script:
  - go test
before_script:
- docker-compose -f ci/docker-compose.yml up -d
services:
- docker