language: go
sudo: required
go:
  - 1.11
install:
  - go get github.com/gorilla/websocket
  - go get github.com/gomodule/redigo/redis
script:
  - mkdir reports
  - go get -u github.com/jstemmer/go-junit-report
  - go test -v | go-junit-report > reports/testcase.xml
  - go test -coverprofile=cover.out && go tool cover -html=cover.out -o reports/coverage.html
  - echo $API_KEY_SECURE
before_script:
  - docker-compose -f ci/docker-compose.yml up -d
services:
  - docker
deploy:
  provider: releases
  api_key:
    secure: eqGDUYZTSmv9UFiAZfTtwRh/SDUBd6iL4HwIuwzpeo47bMfWQBDgVcrfCppi8sizhLqs+UhdZL+iQ4yHbkN89vxZWnfiDIKL3YhwzzHqbZza+ThD6FAhFpq8f4t/uVB1Xq0tjcMJtGrg2/1VJ17DCvstRKJMkmO7ixK4VoqW3lDWlhUZn+QaNK4P0hW0RcpAuUeGmlwLGwzytrp7wAUQ4hxTpRBd9cuf7Cr84i968j5TErqxaFCeB0WWkKHExnzozmgI2jQUNqg15vgqiUm/dJnITC36kgGyjyFY70bbATDfp8Ls208AF93Wfqkp368kBh6ahFb4pCNZSl4lYX715gOVnkPS11Sm8xpIdtz3jHNxCGanfwYFaTUIibsFj/+pZqnfmhWKTzQvkAXlMqKAafZisLGN03W9NxSyAZWunQnT23MR0IvX/C8sK+leWjMec/qtkk7HlWtONHGiGV9KW/ybBnX4fsjyHcaVeTdPGsr2aoehdgdRuLZB72SnG4CE8DCuHbJ331i8aZOVIoEOF9lD+5NIPmiZbcp7+/X4a8z3NosdOBNWCRI6gQVKo4SjDWnB/RdyLiJM9g0SAcsh9qlEfwaWosXT/kO5riQuuuGLLJMmQXktWqnj2PH03dS/XXK1+P/lSW2B0+uqNpPhPR7VZhAWtW+JOVlpkYUjbD4=
  file_glob: true
  file: 'reports/*'
  skip_cleanup: true
  on:
    repo: stevenchiu7311/melody
    all_branches: true